from datetime import date, datetime
from typing import Optional

from sqlmodel import SQLModel, Field


class PntsKod(SQLModel, table=True):
    __tablename__ = "PNTS_KOD"

    # Anahtarlar ve Zorunlu Alanlar
    turu: str = Field(max_length=64, primary_key=True)
    kodu: str = Field(max_length=64, primary_key=True)

    # Diğer Alanlar
    adi: Optional[str] = Field(default=None, max_length=255)
    skrs_kodu: Optional[int] = Field(default=None)
    yontem: Optional[str] = Field(default=None, max_length=1)
    renk_kodu: Optional[int] = Field(default=None)
    min_puan: Optional[int] = Field(default=None)
    max_puan: Optional[int] = Field(default=None)
    hesap_no: Optional[str] = Field(default=None, max_length=64)
    aktif: Optional[int] = Field(default=None)
    tetkik_grubu: Optional[int] = Field(default=None)
    sira: Optional[int] = Field(default=None)
    kk: Optional[int] = Field(default=None)
    maas_katsayisi: Optional[float] = Field(default=None)
    banka_hesap_no: Optional[str] = Field(default=None, max_length=50)
    aciklama: Optional[str] = Field(default=None, max_length=100)
    icerik_miktari: Optional[str] = Field(default=None, max_length=60)
    form: Optional[str] = Field(default=None, max_length=60)
    adet_miktar: Optional[str] = Field(default=None, max_length=60)
    detay: Optional[str] = Field(default=None)  # CLOB için str kullanılır
    hesap_no_ds: Optional[str] = Field(default=None, max_length=16)
    dis_kodu: Optional[int] = Field(default=None)
    parent_turu: Optional[str] = Field(default=None, max_length=64)
    parent_kodu: Optional[str] = Field(default=None, max_length=64)
    onceki_sirasi: Optional[int] = Field(default=None)
    saramatik_baslangic_no: Optional[int] = Field(default=None)
    on_ek: Optional[int] = Field(default=None)
    sql_: Optional[str] = Field(default=None)  # SQL alanı için str kullanılır
    sql_detay: Optional[str] = Field(default=None, max_length=1024)
    banka_adi: Optional[str] = Field(default=None, max_length=100)
    banka_subesi: Optional[str] = Field(default=None, max_length=100)
    adres: Optional[str] = Field(default=None, max_length=200)
    deger: Optional[str] = Field(default=None, max_length=64)
    ent_resmi_kodu: Optional[str] = Field(default=None, max_length=100)
    ent_salon_adi: Optional[str] = Field(default=None, max_length=100)
    tetkik_id: Optional[int] = Field(default=None)
    malzeme_id: Optional[int] = Field(default=None)
    raf_omru_gunu: Optional[int] = Field(default=None)
    vergi_no: Optional[str] = Field(default=None, max_length=64)
    vergi_dairesi: Optional[str] = Field(default=None, max_length=200)
    saklama_sicakligi: Optional[int] = Field(default=None)
    skrs3_kodu: Optional[str] = Field(default=None, max_length=128)
    oncekinden_al: Optional[int] = Field(default=None)
    skrs3_master_kodu: Optional[int] = Field(default=None)
    skrs3_detay_kodu: Optional[str] = Field(default=None, max_length=64)
    medula_kodu: Optional[str] = Field(default=None, max_length=10)
    recete_tipi: Optional[str] = Field(default=None, max_length=10)
    parametreli_test: Optional[int] = Field(default=None)
    kultur_testi: Optional[int] = Field(default=None)
    taburcu_izin_saat: Optional[str] = Field(default=None, max_length=5)
    teslim: Optional[int] = Field(default=None)
    diskatman: Optional[str] = Field(default=None, max_length=10)
    bakanlik_kodu: Optional[str] = Field(default=None, max_length=32)
    modalite: Optional[str] = Field(default=None, max_length=5)
    yurtdisiilac_etkeni: Optional[int] = Field(default=None)
    ip_adresi: Optional[str] = Field(default=None, max_length=64)
    barkod_cihaz_kodu: Optional[str] = Field(default=None, max_length=64)
    port_numarasi: Optional[str] = Field(default=None, max_length=64)
    saat: Optional[float] = Field(default=None)
    barkod_cihaz_kodu2: Optional[str] = Field(default=None, max_length=64)
    vadecum_id: Optional[int] = Field(default=None)
    veri_tipi: Optional[str] = Field(default=None, max_length=64)
    donor_tetkik_id: Optional[int] = Field(default=None)
    dosya: Optional[bytes] = Field(default=None)  # BLOB için bytes kullanılır
    donor_mu: Optional[int] = Field(default=None)
    tetkik_id_4: Optional[int] = Field(default=None)
    tetkik_id_6: Optional[int] = Field(default=None)
    mola_saat: Optional[str] = Field(default=None, max_length=512)
    tetkik_id_0_1: Optional[int] = Field(default=None)
    teletip_gonderilsin: Optional[int] = Field(default=None)
    teletip_mukerrer_sorgulama: Optional[int] = Field(default=None)
    sms_gonder: Optional[int] = Field(default=None)
    fides_gonder: Optional[int] = Field(default=None)
    dk: Optional[float] = Field(default=None)
    dts: Optional[datetime] = Field(default=None)
    kts: Optional[datetime] = Field(default=None)
    kan_yikama_uygunluk_durumu: Optional[float] = Field(default=None)
    kan_isinlama_uygunluk_durumu: Optional[float] = Field(default=None)
    kan_ayirma_uygunluk: Optional[float] = Field(default=None)
    buffycoat_uzaklastirmaya_uygun: Optional[float] = Field(default=None)
    kan_bolme_uygunluk: Optional[float] = Field(default=None)
    kan_filtreleme_uygunluk: Optional[float] = Field(default=None)
    kan_havuzlama_uygunluk: Optional[float] = Field(default=None)
    token: Optional[str] = Field(default=None, max_length=4000)
    token_tarihi: Optional[date] = Field(default=None)
    saat_kontrolu_yapma: Optional[int] = Field(default=None)
    port_adresi: Optional[str] = Field(default=None, max_length=256)
    panates_id: Optional[int] = Field(default=None)
    doktor_teslim: Optional[int] = Field(default=None)
    sendika_odenek_orani: Optional[float] = Field(default=None)
    puantaj_saat: Optional[float] = Field(default=None)
    gonderilme_zamani: Optional[datetime] = Field(default=None)
